language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - jruby-head
matrix:
  include:
    - rvm: 2.4
      os: osx
    - rvm: 2.6
      os: osx
    - rvm: 2.7
      os: osx
  allow_failures:
    - rvm: jruby-head
      
before_install:
- bundle install
before_script: yard gems
script: rspec
