language: ruby
rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - 3.0
  - jruby-head
matrix:
  include:
    - rvm: 2.7
      os: osx
    - rvm: 3.0
      os: osx
  allow_failures:
    - rvm: jruby-head
before_install:
- gem update --system
- gem install bundler
before_script: yard gems
script: rspec
